security:
    encoders:
        App\Entity\User\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: 'bcrypt'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            id: App\Service\User\UserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|develop)/
            security: false

        oauth_token:
            pattern:  ^/api/v1/oauth/token
            security: false

        api_doc:
            pattern:  ^/api/doc
            security: false

        api:
            pattern:    ^/api
            security:   true
            fos_oauth:  true
            provider:   app_user_provider
            stateless:  true
            anonymous:  false # can be omitted as its default value

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/v1,                roles: ROLE_CASH_REGISTER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_CASH_REGISTER